"""initial schema

Revision ID: 839629e4d06a
Revises: 
Create Date: 2026-06-25 15:48:56.936785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '839629e4d06a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Generado con `alembic revision --autogenerate` a partir de los modelos
    actuales de `models.py` (ver CLAUDE.md / memoria de repo para el flujo a
    seguir en futuros cambios de esquema). Reemplaza el `upgrade()` no-op
    original: hasta ahora el esquema se creaba únicamente vía
    `SQLModel.metadata.create_all()` en el arranque de la app, que solo
    puede añadir tablas nuevas, nunca alterar columnas existentes.

    Guardado: si `tema` ya existe (despliegue existente que arrancó con
    `create_all()` antes de que esta migración real existiera, y por tanto
    nunca tuvo `alembic_version` registrada), las tablas ya están creadas y
    no hay nada que hacer aquí — la siguiente migración (`a1c8f3d2e9b4`) se
    encarga de añadir las columnas que falten sobre esas tablas ya
    existentes.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'tema' in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ley', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pregunta_seguridad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('respuesta_seguridad_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('asistentemensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asistentemensaje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistentemensaje_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistentemensaje_tema_id'), ['tema_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistentemensaje_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('asistenteuso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mensajes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asistenteuso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asistenteuso_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_asistenteuso_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('notadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notadia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notadia_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_notadia_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pregunta',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('opciones', sa.JSON(), nullable=False),
    sa.Column('correcta', sa.Integer(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pregunta_tema_id'), ['tema_id'], unique=False)

    op.create_table('sesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.Enum('tema', 'aleatorio', 'simulacro', 'falladas', name='modotest'), nullable=False),
    sa.Column('feedback', sa.Enum('inmediato', 'final', name='feedbackmode'), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('aciertos', sa.Integer(), nullable=False),
    sa.Column('segundos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesion_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('tarjeta',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('frente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dorso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarjeta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarjeta_tema_id'), ['tema_id'], unique=False)

    op.create_table('respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('elegida', sa.Integer(), nullable=True),
    sa.Column('correcta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respuesta_pregunta_id'), ['pregunta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_respuesta_sesion_id'), ['sesion_id'], unique=False)

    op.create_table('tarjetaestado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tarjeta_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_dias', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.Integer(), nullable=False),
    sa.Column('proxima_revision', sa.Date(), nullable=False),
    sa.Column('ultima_revision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjeta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tarjeta_id', name='uq_tarjeta_usuario_tarjeta')
    )
    with op.batch_alter_table('tarjetaestado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarjetaestado_proxima_revision'), ['proxima_revision'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarjetaestado_tarjeta_id'), ['tarjeta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarjetaestado_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarjetaestado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarjetaestado_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tarjetaestado_tarjeta_id'))
        batch_op.drop_index(batch_op.f('ix_tarjetaestado_proxima_revision'))

    op.drop_table('tarjetaestado')
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respuesta_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_respuesta_pregunta_id'))

    op.drop_table('respuesta')
    with op.batch_alter_table('tarjeta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarjeta_tema_id'))

    op.drop_table('tarjeta')
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesion_usuario_id'))

    op.drop_table('sesion')
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pregunta_tema_id'))

    op.drop_table('pregunta')
    with op.batch_alter_table('notadia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notadia_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notadia_fecha'))

    op.drop_table('notadia')
    with op.batch_alter_table('asistenteuso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistenteuso_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_asistenteuso_fecha'))

    op.drop_table('asistenteuso')
    with op.batch_alter_table('asistentemensaje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asistentemensaje_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_asistentemensaje_tema_id'))
        batch_op.drop_index(batch_op.f('ix_asistentemensaje_created_at'))

    op.drop_table('asistentemensaje')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    op.drop_table('tema')
    # ### end Alembic commands ###
